package Literature::ImplicitRelations::ImplicitRelation;

#POD

use strict;
use warnings;


=head1 DESCRIPTION

       This module defines an object to store hidden relationship between node A and node C, based on B node intermediates. 

=head1 METHODS

=cut

=head2 new

  Title: new
  
  Usage: my $inferred_relation = Wbt::Literature::ImplicitRelations::ImplicitRelation->new(A_node_id => 11,
                                                                                           B_nodes => [4454,4453,1112,3435] (reference!),
                                                                                           C_node_id => 134,
										           relation_type => 'Unknown',
										           intermediate_count => 5,
										           known_R_scaled_score => 42,
										           known_literature_count => 12, 
										           avg_inferred_R_scaled_score => 37,
										           min_inferred_R_scaled_score => 34);
  
  Arguments: The object is generated by the hidden relationship analysis routines in the DB::CopubSara module.
             This object includes:
	       
	       A_node_id: node A (biologicalitem id).
	       B_node_ids: array of B intermediates (biologicalitem id).
	       C_node_id: node C (biologicalitem_id).
	       relationship_type: 'Known' or 'Unknown'.
	       intermediate_count: number of intermediates (B-nodes).
	       B_node_literature_count_threshold: threshold for number of co-publications between A and B, and between B and C.
	       R_scaled_threshold_B_node: threshold for R-scaled score between A and B, and between B and C.
	       intermediate_type: _1_ (genes only), or _1_23_ (genes + merged biological processes and pathways).
	       known_R_scaled_score: R-scaled score between A and C in literature.
	       known_literature_count: co-publication count between A and C in literature.
	       avg_inferred_R_scaled_score: avg_inferred_R_scaled_score between A and C.
	       min_inferred_R_scaled_score: min_inferred_R_scaled_score between A and C.
  
  Return: A Wbt::Literature::ImplicitRelations::ImplicitRelation object

=cut

sub new {
    my ($caller, %args) = @_;
    my $self = bless {
                 %args
    }, ref $caller || $caller;
    return $self;
}

1;
